version: '3.1'
services:
  aidbox-ts-generator:
    image: "bedasoftware/aidbox-ts-generator:latest"
    command: ["-o", "/tmp/aidbox.d.ts", "-u", "http://devbox:8080", "--user", "$AIDBOX_CLIENT_ID", "--pass", "$AIDBOX_CLIENT_SECRET"]
    depends_on:
      - backend
    links:
      - "devbox:devbox"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./contrib/aidbox-types/index.d.ts:/tmp/aidbox.d.ts
