services:
  build-seeds:
    image: bedasoftware/fhirsnake
    command:
        - export
        - --output
        - /app/zenproject/seeds.ndjson.gz
    volumes:
        - ./zenproject:/app/zenproject
        - ./resources/seeds:/app/resources

