import {
    GroupItemComponent,
    ItemControlGroupItemComponentMapping,
    ItemControlQuestionItemComponentMapping,
    QuestionItemComponentMapping,
} from 'sdc-qrf';

import {
    AudioRecorderUploader,
    Barcode,
    BloodPressure,
    Col,
    Display,
    EditableGroup,
    Grid,
    Group,
    GroupTable,
    GroupTabs,
    GroupWizard,
    GroupWizardVertical,
    GroupWizardWithTooltips,
    Gtable,
    InlineChoice,
    InlineReference,
    MainCard,
    MDEditorControl,
    PasswordInput,
    QuestionBoolean,
    QuestionChoice,
    QuestionDateTime,
    QuestionDecimal,
    QuestionEmail,
    QuestionInputInsideText,
    QuestionInteger,
    QuestionPhone,
    QuestionQuantity,
    QuestionReference,
    QuestionSlider,
    QuestionSolidRadio,
    QuestionString,
    QuestionText,
    Row,
    Section,
    SectionWithDivider,
    SubCard,
    TextWithMacroFill,
    TimeRangePickerControl,
    UploadFileControl,
} from '@beda.software/web-item-controls/controls';
import {
    AnxietyScore,
    DepressionScore,
    MarkdownCard,
    MarkdownDisplay,
} from '@beda.software/web-item-controls/readonly-controls';

export const itemComponents: QuestionItemComponentMapping = {
    text: QuestionText,
    string: QuestionString,
    decimal: QuestionDecimal,
    integer: QuestionInteger,
    date: QuestionDateTime,
    dateTime: QuestionDateTime,
    time: QuestionDateTime,
    choice: QuestionChoice,
    'open-choice': QuestionChoice,
    boolean: QuestionBoolean,
    display: Display,
    reference: QuestionReference,
    quantity: QuestionQuantity,
    attachment: UploadFileControl,
};

export const groupComponent: GroupItemComponent = Group;

export const itemControlComponents: ItemControlQuestionItemComponentMapping = {
    phoneWidget: QuestionPhone,
    email: QuestionEmail,
    passwordWidget: PasswordInput,
    slider: QuestionSlider,
    'solid-radio-button': QuestionSolidRadio,
    'inline-choice': InlineChoice,
    'inline-reference': InlineReference,
    'text-with-macro': TextWithMacroFill,
    'radio-button': InlineChoice,
    'check-box': InlineChoice,
    'input-inside-text': QuestionInputInsideText,
    'markdown-editor': MDEditorControl,
    'audio-recorder-uploader': AudioRecorderUploader,
    barcode: Barcode,
    markdown: MarkdownDisplay,
    'markdown-card': MarkdownCard,
    // reference-radio-button is deprecated, use inline-reference instead
    'reference-radio-button': InlineReference,
    'anxiety-score': AnxietyScore,
    'depression-score': DepressionScore,
};

export const groupControlComponents: ItemControlGroupItemComponentMapping = {
    col: Col,
    row: Row,
    gtable: Gtable,
    table: Gtable,
    grid: Grid,
    section: Section,
    'section-with-divider': SectionWithDivider,
    'main-card': MainCard,
    'sub-card': SubCard,
    'blood-pressure': BloodPressure,
    'time-range-picker': TimeRangePickerControl,
    wizard: GroupWizard,
    'wizard-with-tooltips': GroupWizardWithTooltips,
    'wizard-navigation-group': GroupWizard,
    'wizard-vertical': GroupWizardVertical,
    'group-tabs': GroupTabs,
    'group-table': GroupTable,
    'editable-group': EditableGroup,
};
